language: objective-c
before_install:
  - gem install xcpretty -N
  - gem install cocoapods --pre --quiet
  - gem install slather
  - pod setup --silent
  - pod repo update --silent
script:
  - set -o pipefail
  - xcodebuild -project HelloWorld.xcodeproj -sdk iphonesimulator -scheme HelloWorld test | xcpretty -c
after_success:
  - slather
