language: objective-c
install:
  - brew update
  - brew unlink xctool
  - brew install xctool

script:
  - xctool test -project HelloWorld.xcodeproj -scheme HelloWorld -sdk iphonesimulator8.3 -destination "platform=iOS Simulator,OS=8.3,name=iPhone 6"
